DECLARE
    id SAMPLE.ID%TYPE:=100;
BEGIN
    SELECT ID INTO id
    FROM SAMPLE
    WHERE ID=id;
    DBMS_OUTPUT.PUT_LINE('Found Exactly One Id: '|| id);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO SUCH ID');
    WHEN OTHERS THEN   
        DBMS_OUTPUT.PUT_LINE('ERROR !');
END;
/