CREATE OR REPLACE TRIGGER DISPLAY_COUNT_ID
BEFORE DELETE OR INSERT OR UPDATE ON SAMPLE
FOR EACH ROW
DECLARE
    totCount int;
BEGIN
    SELECT COUNT(ID) INTO totCount FROM SAMPLE;
    DBMS_OUTPUT.PUT_LINE('Total Id count after update: ' || totCount);
END;
/